import os
from typing import List, Dict, Any, Optional
import openai

def analyze_tech_stack(file_tree: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Analyzes file extensions and filenames in the tree to infer tech stack & architecture.
    """
    languages = {}
    entry_points = []
    config_files = []
    key_dirs = set()

    for item in file_tree:
        path = item.get("path", "")
        lang = item.get("language", "other")

        # Track language distribution
        languages[lang] = languages.get(lang, 0) + 1

        # Track directory structure
        parts = path.split("/")
        if len(parts) > 1:
            key_dirs.add(parts[0])

        filename = parts[-1].lower()

        # Identify potential entry points
        if filename in ["main.py", "app.py", "server.js", "index.js", "main.jsx", "index.html", "manage.py"]:
            entry_points.append(path)

        # Identify config / dependency files
        if filename in ["requirements.txt", "package.json", "dockerfile", "render.yaml", "vercel.json", "pyproject.toml", "setup.py"]:
            config_files.append(path)

    # Convert language counts to percentages
    total_files = len(file_tree) or 1
    lang_stats = [
        {"language": lang, "count": count, "percentage": round((count / total_files) * 100, 1)}
        for lang, count in sorted(languages.items(), key=lambda x: x[1], reverse=True)
    ]

    return {
        "languages": lang_stats,
        "entry_points": entry_points,
        "config_files": config_files,
        "key_directories": sorted(list(key_dirs)),
        "total_files": len(file_tree)
    }

def synthesize_onboarding_fallback(owner: str, repo: str, analysis: Dict[str, Any], chunks: List[Dict[str, Any]]) -> str:
    """
    Generates a structured developer onboarding brief when no LLM API key is present.
    """
    lang_list = ", ".join([f"**{item['language']}** ({item['percentage']}%)" for item in analysis["languages"][:4]])
    entry_str = "\n".join([f"- `{ep}`" for ep in analysis["entry_points"]]) if analysis["entry_points"] else "- *Standard framework entry point*"
    config_str = "\n".join([f"- `{cf}`" for cf in analysis["config_files"]]) if analysis["config_files"] else "- *Standard environment configuration*"
    dirs_str = ", ".join([f"`{d}/`" for d in analysis["key_directories"][:6]]) if analysis["key_directories"] else "`root`"

    snippet_overview = ""
    if chunks:
        top_snippet = chunks[0].get("content", "").strip()[:300]
        first_file = chunks[0].get("metadata", {}).get("file_path", "codebase")
        snippet_overview = f"\n### 🔍 Initial Codebase Inspection (`{first_file}`)\n```code\n{top_snippet}\n```\n"

    brief = (
        f"# 🧭 Repository Onboarding Brief: `{owner}/{repo}`\n\n"
        f"> **Welcome Developer!** This onboarding brief was auto-generated by **CodeCompass** to help you understand the architecture, tech stack, and key entry points of this repository in minutes.\n\n"
        f"---\n\n"
        f"## 📊 Tech Stack & Language Breakdown\n"
        f"- **Primary Languages:** {lang_list}\n"
        f"- **Total Source Files Parsed:** `{analysis['total_files']}` files\n"
        f"- **Core Directory Layout:** {dirs_str}\n\n"
        f"---\n\n"
        f"## 🚀 Key Entry Points & Configuration\n"
        f"### Primary Code Entry Points:\n"
        f"{entry_str}\n\n"
        f"### Build & Dependency Configurations:\n"
        f"{config_str}\n\n"
        f"---\n\n"
        f"## 🏗️ Architecture Overview & Data Flow\n"
        f"This repository follows a structured component-based architecture organized around `{dirs_str}`. "
        f"Business logic and API handlers are routed through entry points like {entry_str.splitlines()[0] if entry_str else 'main application module'}.\n"
        f"{snippet_overview}\n"
        f"---\n\n"
        f"## ⚡ Quick Setup & How to Run\n"
        f"1. **Clone Repository:** `git clone https://github.com/{owner}/{repo}.git`\n"
        f"2. **Inspect Dependencies:** Review configuration files ({config_str.replace('- ', '') if config_str else 'package manifests'}).\n"
        f"3. **Run Application:** Execute primary entry point scripts to boot local dev environment.\n\n"
        f"---\n\n"
        f"## 💡 Recommended Exploration Questions\n"
        f"- *\"What is the main entry point of this codebase and how does execution start?\"*\n"
        f"- *\"How are errors and API responses handled across services?\"*\n"
        f"- *\"What third-party packages or frameworks does this project rely on?\"*\n"
    )
    return brief

def generate_onboarding_brief(
    owner: str,
    repo: str,
    file_tree: List[Dict[str, Any]],
    chunks: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Generates an auto-generated Repository Onboarding Brief using Gemini API, OpenAI, or a smart fallback synthesizer.
    """
    analysis = analyze_tech_stack(file_tree)
    openai_key = os.getenv("OPENAI_API_KEY", "").strip()
    gemini_key = os.getenv("GEMINI_API_KEY", "").strip()

    system_prompt = (
        "You are CodeCompass, a Senior Software Architect. "
        "Generate a comprehensive, beautifully formatted Markdown Developer Onboarding Brief for a newly ingested GitHub repository. "
        "Include sections for Overview, Tech Stack Breakdown, Architecture & Data Flow, Key Entry Points, Quick Start, and 3 Suggested Questions."
    )

    context_summary = (
        f"Repository: {owner}/{repo}\n"
        f"Total Files: {analysis['total_files']}\n"
        f"Languages: {analysis['languages']}\n"
        f"Entry Points: {analysis['entry_points']}\n"
        f"Config Files: {analysis['config_files']}\n"
        f"Directories: {analysis['key_directories']}\n"
    )

    markdown_brief = None

    if openai_key and openai_key != "your_openai_api_key_here":
        try:
            client = openai.OpenAI(api_key=openai_key)
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Repository Metadata:\n{context_summary}\n\nGenerate the complete Markdown onboarding brief."}
                ],
                temperature=0.3,
                max_tokens=1000
            )
            markdown_brief = response.choices[0].message.content
        except Exception as e:
            print(f"[Onboarding Warning] OpenAI call failed: {e}")

    if not markdown_brief and gemini_key and gemini_key != "your_gemini_api_key_here":
        try:
            import google.generativeai as genai
            genai.configure(api_key=gemini_key)
            model = genai.GenerativeModel("gemini-1.5-flash")
            res = model.generate_content(f"{system_prompt}\n\nRepository Metadata:\n{context_summary}")
            markdown_brief = res.text
        except Exception as e:
            print(f"[Onboarding Warning] Gemini call failed: {e}")

    if not markdown_brief:
        markdown_brief = synthesize_onboarding_fallback(owner, repo, analysis, chunks)

    return {
        "status": "success",
        "owner": owner,
        "repo": repo,
        "analysis": analysis,
        "onboarding_brief": markdown_brief,
        "suggested_questions": [
            "What is the main entry point and how does execution start?",
            "How are environment variables and configurations managed?",
            "What architectural pattern is used for modules and components?",
            "Where are external APIs or database calls implemented?"
        ]
    }
