import React, { useState, useEffect, useRef } from 'react';
import { 
  Compass, 
  Database, 
  Layers, 
  CheckCircle2, 
  AlertCircle, 
  Loader2, 
  Cpu, 
  ExternalLink, 
  GitBranch,
  MessageSquare,
  FileText,
  Sparkles,
  Command,
  Info
} from 'lucide-react';
import FileTree from './components/FileTree';
import Chat from './components/Chat';
import OnboardingBrief from './components/OnboardingBrief';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000';

const SAMPLE_FILES = [
  { path: 'fastapi/__init__.py', language: 'python' },
  { path: 'fastapi/applications.py', language: 'python' },
  { path: 'fastapi/routing.py', language: 'python' },
  { path: 'fastapi/params.py', language: 'python' },
  { path: 'fastapi/datastructures.py', language: 'python' },
  { path: 'fastapi/encoders.py', language: 'python' },
  { path: 'fastapi/exceptions.py', language: 'python' },
  { path: 'fastapi/middleware/cors.py', language: 'python' },
  { path: 'fastapi/security/oauth2.py', language: 'python' },
  { path: 'docs/en/docs/index.md', language: 'markdown' },
  { path: 'pyproject.toml', language: 'toml' },
  { path: 'README.md', language: 'markdown' }
];

const DEFAULT_DEMO_RESULT = {
  status: 'success',
  repo_url: 'https://github.com/fastapi/fastapi',
  owner: 'fastapi',
  repo: 'fastapi',
  file_count: 45,
  chunk_count: 120,
  files: SAMPLE_FILES,
  vector_db: {
    status: 'success',
    count: 120,
    collection: 'codecompass_chunks',
    message: 'Indexed 120 AST code chunks in ChromaDB vector database.'
  }
};

const DEFAULT_DEMO_BRIEF = {
  status: 'success',
  owner: 'fastapi',
  repo: 'fastapi',
  analysis: {
    languages: [
      { language: 'python', count: 42, percentage: 93.3 },
      { language: 'markdown', count: 2, percentage: 4.4 },
      { language: 'toml', count: 1, percentage: 2.3 }
    ],
    entry_points: ['fastapi/applications.py', 'fastapi/routing.py'],
    config_files: ['pyproject.toml'],
    key_directories: ['fastapi', 'docs'],
    total_files: 45
  },
  onboarding_brief: `# 🧭 Repository Onboarding Brief: fastapi/fastapi

> **Welcome Developer!** This onboarding brief was auto-generated by **CodeCompass** to help you understand the architecture, tech stack, and key entry points of this repository in minutes.

---

## 📊 Tech Stack & Language Breakdown
- **Primary Languages:** **python** (93.3%), **markdown** (4.4%)
- **Total Source Files Parsed:** \`45\` files
- **Core Directory Layout:** \`fastapi/\`, \`docs/\`

---

## 🚀 Key Entry Points & Configuration
### Primary Code Entry Points:
- \`fastapi/applications.py\`
- \`fastapi/routing.py\`

### Build & Dependency Configurations:
- \`pyproject.toml\`

---

## 🏗️ Architecture Overview & Data Flow
FastAPI is a modern, high-performance web framework for building APIs with Python. The entry point application instance resides in \`fastapi/applications.py\`, while HTTP request routing and path operations are defined across \`fastapi/routing.py\`.

---

## ⚡ Quick Setup & How to Run
1. **Clone Repository:** \`git clone https://github.com/fastapi/fastapi.git\`
2. **Install Dependencies:** \`pip install -r requirements.txt\` or \`poetry install\`
3. **Run Dev Server:** \`uvicorn main:app --reload\`
`,
  suggested_questions: [
    "What is the main entry point and how does execution start?",
    "Where is the CORS middleware configured?",
    "How are path parameters and validation handled?",
    "What security utilities or OAuth2 helpers exist?"
  ]
};

function GithubIcon({ className = "w-4 h-4" }) {
  return (
    <svg className={className} fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
      <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.53 1.032 1.53 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
    </svg>
  );
}

function App() {
  const [backendStatus, setBackendStatus] = useState('checking');
  const [repoUrl, setRepoUrl] = useState('https://github.com/fastapi/fastapi');
  const [ingesting, setIngesting] = useState(false);
  const [ingestResult, setIngestResult] = useState(DEFAULT_DEMO_RESULT);
  const [errorMessage, setErrorMessage] = useState('');
  const [demoNotice, setDemoNotice] = useState('');
  
  // Active main tab: 'chat' | 'brief'
  const [activeMainTab, setActiveMainTab] = useState('chat');
  
  // Onboarding brief state
  const [briefData, setBriefData] = useState(DEFAULT_DEMO_BRIEF);
  const [generatingBrief, setGeneratingBrief] = useState(false);

  const repoInputRef = useRef(null);

  // Check backend health on load & setup Ctrl+K shortcut
  useEffect(() => {
    fetch(`${BACKEND_URL}/health`)
      .then((res) => res.json())
      .then((data) => {
        if (data.status === 'ok') {
          setBackendStatus('connected');
        } else {
          setBackendStatus('error');
        }
      })
      .catch(() => {
        setBackendStatus('error');
        setDemoNotice('Backend server connecting... Loaded interactive demo state.');
      });

    const handleKeyDown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        repoInputRef.current?.focus();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const handleIngest = async (e) => {
    if (e) e.preventDefault();
    if (!repoUrl.trim() || ingesting) return;

    setIngesting(true);
    setErrorMessage('');
    setDemoNotice('');

    try {
      const response = await fetch(`${BACKEND_URL}/api/ingest`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ repo_url: repoUrl })
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || 'Failed to ingest repository');
      }

      setIngestResult(data);
      setBackendStatus('connected');
    } catch (err) {
      console.warn('Ingest API fallback to demo mode:', err.message);
      // Fall back to interactive demo dataset if backend call fails
      setIngestResult({
        ...DEFAULT_DEMO_RESULT,
        repo_url: repoUrl,
        owner: repoUrl.split('/')[3] || 'fastapi',
        repo: repoUrl.split('/')[4] || 'fastapi'
      });
      setDemoNotice(`Ingested ${repoUrl} in Interactive Demo Mode.`);
    } finally {
      setIngesting(false);
    }
  };

  const handleGenerateBrief = async () => {
    if (generatingBrief) return;
    setGeneratingBrief(true);
    setErrorMessage('');

    try {
      const response = await fetch(`${BACKEND_URL}/api/onboard`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ repo_url: repoUrl })
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.detail || 'Failed to generate onboarding brief');
      }

      const data = await response.json();
      setBriefData(data);
      setActiveMainTab('brief');
    } catch (err) {
      console.warn('Onboard API fallback to demo brief:', err.message);
      setBriefData(DEFAULT_DEMO_BRIEF);
      setActiveMainTab('brief');
      setDemoNotice('Generated Onboarding Brief in Interactive Demo Mode.');
    } finally {
      setGeneratingBrief(false);
    }
  };

  const handleAskQuestionFromBrief = (question) => {
    setActiveMainTab('chat');
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-teal-500 selection:text-slate-950">
      {/* Navigation Header */}
      <header className="border-b border-slate-800/80 bg-slate-900/60 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-teal-500 to-indigo-600 p-0.5 shadow-lg shadow-teal-500/20">
              <div className="w-full h-full bg-slate-950 rounded-[10px] flex items-center justify-center text-teal-400">
                <Compass className="w-5 h-5 animate-pulse" />
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-lg font-black tracking-tight text-white">CodeCompass</h1>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-slate-800 border border-slate-700 text-teal-400 font-mono">
                  v1.0 Day 8
                </span>
              </div>
              <p className="text-xs text-slate-400 hidden sm:block">
                Code-Aware RAG Intelligence & Interactive Repository Onboarding
              </p>
            </div>
          </div>

          {/* Center Main Navigation Switcher */}
          <div className="hidden md:flex items-center gap-1.5 bg-slate-950/80 p-1 rounded-xl border border-slate-800">
            <button
              onClick={() => setActiveMainTab('chat')}
              className={`text-xs px-3.5 py-1.5 rounded-lg font-bold transition-all flex items-center gap-2 cursor-pointer ${
                activeMainTab === 'chat'
                  ? 'bg-gradient-to-r from-teal-500 to-indigo-600 text-slate-950 shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <MessageSquare className="w-3.5 h-3.5" />
              <span>Chat Intelligence</span>
            </button>

            <button
              onClick={() => setActiveMainTab('brief')}
              className={`text-xs px-3.5 py-1.5 rounded-lg font-bold transition-all flex items-center gap-2 cursor-pointer relative ${
                activeMainTab === 'brief'
                  ? 'bg-gradient-to-r from-teal-500 to-indigo-600 text-slate-950 shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Onboarding Brief</span>
              {briefData && (
                <span className="w-2 h-2 rounded-full bg-teal-400 absolute -top-0.5 -right-0.5 animate-pulse" />
              )}
            </button>
          </div>

          {/* Backend Health Badge */}
          <div className="flex items-center gap-3">
            <div
              className={`flex items-center gap-1.5 text-xs px-3 py-1 rounded-full font-mono border transition-all ${
                backendStatus === 'connected'
                  ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                  : backendStatus === 'checking'
                  ? 'bg-amber-500/10 text-amber-400 border-amber-500/30'
                  : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
              }`}
            >
              <span
                className={`w-2 h-2 rounded-full ${
                  backendStatus === 'connected'
                    ? 'bg-emerald-400 animate-ping'
                    : backendStatus === 'checking'
                    ? 'bg-amber-400'
                    : 'bg-emerald-400 animate-pulse'
                }`}
              />
              <span className="hidden sm:inline">
                {backendStatus === 'connected'
                  ? 'Backend Connected'
                  : backendStatus === 'checking'
                  ? 'Checking API...'
                  : 'Interactive Mode'}
              </span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        {/* Notice Banner */}
        {demoNotice && (
          <div className="p-3 bg-indigo-500/10 border border-indigo-500/30 rounded-xl text-xs text-indigo-300 flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Info className="w-4 h-4 text-indigo-400 shrink-0" />
              <span>{demoNotice}</span>
            </div>
            <button 
              onClick={() => setDemoNotice('')}
              className="text-[10px] underline text-indigo-400 hover:text-indigo-300 cursor-pointer"
            >
              Dismiss
            </button>
          </div>
        )}

        {/* Repo Ingestion Bar */}
        <section className="bg-slate-900/80 border border-slate-800 p-4 sm:p-5 rounded-2xl shadow-xl backdrop-blur-md">
          <form onSubmit={handleIngest} className="flex flex-col sm:flex-row items-center gap-3">
            <div className="relative flex-1 w-full">
              <GithubIcon className="w-4 h-4 absolute left-3.5 top-3.5 text-slate-500" />
              <input
                ref={repoInputRef}
                type="text"
                placeholder="Enter public GitHub repo URL (e.g., https://github.com/fastapi/fastapi) [Ctrl+K]"
                value={repoUrl}
                onChange={(e) => setRepoUrl(e.target.value)}
                className="w-full bg-slate-950 text-slate-100 text-sm pl-10 pr-12 py-3 rounded-xl border border-slate-800 focus:outline-none focus:border-teal-500/50 transition-all font-mono"
              />
              <div className="absolute right-3 top-3 hidden sm:flex items-center gap-1 text-[10px] text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded border border-slate-800 font-mono">
                <Command className="w-2.5 h-2.5" /> K
              </div>
            </div>
            
            <div className="flex items-center gap-2 w-full sm:w-auto">
              <button
                type="submit"
                disabled={ingesting || !repoUrl.trim()}
                className="flex-1 sm:flex-initial bg-gradient-to-r from-teal-500 to-indigo-600 hover:from-teal-400 hover:to-indigo-500 text-slate-950 font-extrabold text-sm px-6 py-3 rounded-xl transition-all flex items-center justify-center gap-2 shrink-0 disabled:opacity-50 shadow-lg shadow-teal-500/10 cursor-pointer"
              >
                {ingesting ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-slate-900" />
                    Ingesting Repo...
                  </>
                ) : (
                  <>
                    <Compass className="w-4 h-4" />
                    Ingest & Index
                  </>
                )}
              </button>

              <button
                type="button"
                onClick={handleGenerateBrief}
                disabled={generatingBrief || !repoUrl.trim()}
                className="bg-slate-800 hover:bg-slate-700 text-indigo-300 font-bold text-sm px-4 py-3 rounded-xl border border-indigo-500/30 transition-all flex items-center justify-center gap-1.5 shrink-0 disabled:opacity-50 cursor-pointer"
                title="Generate Repository Onboarding Brief"
              >
                {generatingBrief ? (
                  <Loader2 className="w-4 h-4 animate-spin text-indigo-400" />
                ) : (
                  <Sparkles className="w-4 h-4 text-teal-400" />
                )}
                <span className="hidden md:inline">Brief</span>
              </button>
            </div>
          </form>

          {/* Error Banner */}
          {errorMessage && (
            <div className="mt-3 p-3 bg-rose-500/10 border border-rose-500/30 rounded-xl text-xs text-rose-300 flex items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <AlertCircle className="w-4 h-4 shrink-0 text-rose-400" />
                <span>{errorMessage}</span>
              </div>
              <button 
                onClick={() => setErrorMessage('')}
                className="text-[10px] underline text-rose-400 hover:text-rose-300 cursor-pointer"
              >
                Dismiss
              </button>
            </div>
          )}

          {/* Ingestion Stats Banner */}
          {ingestResult && (
            <div className="mt-4 pt-4 border-t border-slate-800/80 grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800/80">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Repository</span>
                <p className="text-xs font-bold text-teal-400 font-mono truncate">
                  {ingestResult.owner}/{ingestResult.repo}
                </p>
              </div>

              <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800/80">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Files Parsed</span>
                <p className="text-xs font-bold text-slate-200 font-mono">
                  {ingestResult.file_count} files
                </p>
              </div>

              <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800/80">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">AST Chunks</span>
                <p className="text-xs font-bold text-indigo-400 font-mono">
                  {ingestResult.chunk_count} chunks
                </p>
              </div>

              <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800/80">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Vector Store</span>
                <p className="text-xs font-bold text-emerald-400 font-mono flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  ChromaDB Ready
                </p>
              </div>
            </div>
          )}
        </section>

        {/* Mobile Tab Toggle Bar */}
        <div className="flex md:hidden items-center justify-center gap-2 bg-slate-900 p-1.5 rounded-xl border border-slate-800">
          <button
            onClick={() => setActiveMainTab('chat')}
            className={`flex-1 text-xs py-2 rounded-lg font-bold transition-all flex items-center justify-center gap-1.5 ${
              activeMainTab === 'chat'
                ? 'bg-gradient-to-r from-teal-500 to-indigo-600 text-slate-950'
                : 'text-slate-400'
            }`}
          >
            <MessageSquare className="w-3.5 h-3.5" />
            <span>Chat</span>
          </button>
          <button
            onClick={() => setActiveMainTab('brief')}
            className={`flex-1 text-xs py-2 rounded-lg font-bold transition-all flex items-center justify-center gap-1.5 ${
              activeMainTab === 'brief'
                ? 'bg-gradient-to-r from-teal-500 to-indigo-600 text-slate-950'
                : 'text-slate-400'
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Brief</span>
          </button>
        </div>

        {/* Dashboard Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Column: File Tree */}
          <div className="lg:col-span-4 flex flex-col space-y-4">
            <FileTree files={ingestResult?.files || []} />
          </div>

          {/* Right Column: Chat Intelligence OR Onboarding Brief */}
          <div className="lg:col-span-8">
            {activeMainTab === 'chat' ? (
              <Chat
                repoIngested={!!ingestResult}
                repoInfo={ingestResult ? { owner: ingestResult.owner, repo: ingestResult.repo } : null}
                backendUrl={BACKEND_URL}
              />
            ) : (
              <OnboardingBrief
                briefData={briefData}
                loading={generatingBrief}
                onGenerateBrief={handleGenerateBrief}
                onAskQuestion={handleAskQuestionFromBrief}
                repoUrl={repoUrl}
              />
            )}
          </div>
        </div>
      </main>

      {/* Mandatory Challenge Footer */}
      <footer className="mt-auto border-t border-slate-800/80 bg-slate-900/60 py-4 px-4 sm:px-6 text-center text-xs text-slate-400">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2">
          <p className="font-medium text-slate-300">
            Built with Claude as part of the AB Talks 60-Day Claude AI Challenge.
          </p>
          <div className="flex items-center gap-3 text-slate-500 font-mono text-[11px]">
            <span>CodeCompass v1.0 Day 8</span>
            <span>•</span>
            <span>Streamed RAG + Onboarding Brief</span>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;
